name: Daily Pelican Build

on:
  schedule:
    - cron: '0 4 * * *'  # Daily at 4 AM UTC
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch data and generate content
        run: |
          python fetch_data.py

      - name: Build the site
        run: |
          pelican content -o output -s pelicanconf.py

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          pip install ghp-import
          ghp-import output -b gh-pages
          git push -f origin gh-pages
